import Footer from '../components/Footer';
import Header from '../components/Header';
import Name from '../components/Name';
import Head from 'next/head';

import { createClient } from '@supabase/supabase-js'
import { useEffect, useState } from 'react';
import { useSupabaseClient } from '@supabase/auth-helpers-react';



export default function Home() {
const supabase = useSupabaseClient()
const [name,setNames]=useState("Hello World!")   
const [data,setData]=useState([])
const fetchNames = async() => {const { data, error } = await supabase.from('test').select('*')
if (error){console.log(error)}else {console.log(data); setData(data)}}

useEffect(() => {fetchNames() 
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, [data])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Header />
            {data.map(row=>(<Name name={row.name} key={row.name} />))}
            <div>{name}</div>
            <button className='bg-blue-100 p-1 border rounded-full hover:bg-red-200 hover:shadow-lg transition duration-100' onClick={()=>{setNames('Poo')}}>Click Me!</button>
            <div className='text-red-500 bg-blue-100 items-center justify-center p-1 hover:bg-yellow-400 w-36 lg:w-[400px] flex-auto rounded-full flex'>Hello World</div>
            <Footer />
        </>
    );
}
